AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket holding tv shows
Parameters:
  BucketName:
    Description: Bucket to store tv shows
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref 'BucketName'
